version: "3"
services:
  hello-play:
    build: .
    volumes:
      - ./hello-play:/root/hello-play
      - ./hello-play-ivy-cache:/root/.ivy2
    working_dir: /root/hello-play
    command: sbt -mem 3072 run
    tty: true
    stdin_open: true
    ports:
      - 9000:9000